In [1]:
import numpy as np

# 자세한 설명은 junsoofeb.github.io
# forward()와 backward()는 np.array를 인수로 받는다고 가정했다.

In [2]:
# mask는 True/False로 구성된 넘파이 배열이다.
# 순전파의 입력x가 0보다 크면 False, 0이하면 True이다.

class ReLU:
    def __init__(self):
        self.mask = None

    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0

        return out

    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout

        return dx

In [3]:
# sigmoid 역전파의 최종 출력은 dy/dx = dL/dyㆍy^2ㆍe^-x가 나온다. L은 역전파의 초기값이다.
# 순전파의 입력x와 출력y 만으로 계산 가능함을 알 수 있다.
# y = 1 / 1 + e^-x 이므로 y를 이 값으로 대입하면, 출력y만으로 표현할 수 있다. dy/dx = dL/dyㆍy(1-y)

class sigmoid:
    def __init__(self):
        self.out = None

    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out

        return out

    def backward(self, dout): # dy/dx = dL/dyㆍy(1-y)
        dx = dout * (1.0 - self.out) * self.out

        return dx

In [4]:
relu = ReLU()
sig = sigmoid()

In [5]:
forward1 = relu.forward(np.array([[1.0], [-0.5]]))
backward1 = relu.backward(np.array([[-2.0], [3.0]]))


print("1과 -0.5가 입력일 때, 각각에 대한 ReLU 함수의 순전파 :\n", forward1)
# 입력값이 0보다 크면 그대로 출력하고, 입력값이 0 이하면 출력은 0

print("\n")

print("-2와 3이 상류에서 들어올 때, 각각에 대한 ReLU 함수의 역전파 : \n", backward1)
# 입력이 0보다 컸던 곳으로는 상류의 값을 그대로 전파하고, 입력이 0이하였던 곳은 0을 전파한다.

1과 -0.5가 입력일 때, 각각에 대한 ReLU 함수의 순전파 :
 [[1.]
 [0.]]


-2와 3이 상류에서 들어올 때, 각각에 대한 ReLU 함수의 역전파 : 
 [[-2.]
 [ 0.]]


In [6]:
forward2 = sig.forward(np.array([[2.0], [-0.5]]))
backward2 = sig.backward(np.array([[-2.0], [3.0]]))


print("1과 -0.5가 입력일 때, 각각에 대한 sigmoid 함수의 순전파 :\n", forward2)

print("\n")

print("-2와 3이 상류에서 들어올 때, 각각에 대한 sigmoid 함수의 역전파 : \n", backward2)

1과 -0.5가 입력일 때, 각각에 대한 sigmoid 함수의 순전파 :
 [[0.88079708]
 [0.37754067]]


-2와 3이 상류에서 들어올 때, 각각에 대한 sigmoid 함수의 역전파 : 
 [[-0.20998717]
 [ 0.70501114]]
