In [1]:
import numpy as np

# 행렬의 내적을 기하학에서는 어파인(affine) 변환이라고 한다.
# 노드와 노드사이에 스칼라가 아닌 행렬이 흐르기 때문에 shape를 맞춰주어야 한다.

In [2]:
class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
        
    def forward(self, x):
        self.x = x
        out = np.dot(x, self.W) + self.b
        
        return out
    
    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)
        
        return dx

In [3]:
x = np.array([[1], [2]]) 
W = np.array([[3,  4]])
b = np.array([[10, 20], [30, 40]])

print("x :\n",x,"\n\nW :\n", W,"\n\nb :\n", b,"\n")


print("x의 shape :",x.shape,"\nW의 shape :", W.shape,"\nb의 shape :", b.shape,"\n")


mat = Affine(W,b)

print("xW + b는? \n",mat.forward(x),"\n")

dout = np.array([[1, 1], [1, 1]])

print("x에 대한 L의 미분은? :\n",mat.backward(dout))

x :
 [[1]
 [2]] 

W :
 [[3 4]] 

b :
 [[10 20]
 [30 40]] 

x의 shape : (2, 1) 
W의 shape : (1, 2) 
b의 shape : (2, 2) 

xW + b는? 
 [[13 24]
 [36 48]] 

x에 대한 L의 미분은? :
 [[7]
 [7]]
